# Ubuntu 15.04 with Java 8 installed
 
FROM adoptopenjdk:8-jdk-hotspot
RUN apt-get update && \
	apt-get install unzip && \
    apt-get clean
	
ADD build/distributions/Exchange.MatchingEngine-1.0.zip .
RUN unzip -q Exchange.MatchingEngine-1.0.zip && \
    rm Exchange.MatchingEngine-1.0.zip && \
    mv Exchange.MatchingEngine-* Exchange.MatchingEngine && \
    chmod +x Exchange.MatchingEngine/bin/start.sh && \
    chmod +x Exchange.MatchingEngine/bin/stop.sh && \
    sed -i -e 's/\r$//' Exchange.MatchingEngine/bin/start.sh && \
    sed -i -e 's/\r$//' Exchange.MatchingEngine/bin/stop.sh

EXPOSE 4000 4001 4002 4003

ENTRYPOINT ["/Exchange.MatchingEngine/bin/start.sh"]
CMD ["--console"]